server:
  port: 8081

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true


  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
